classdef BaseModelOptimizationTest < matlab.unittest.TestCase
    %BaseModelOptimizationTest - Compare the base model with GAMS results
    %   BaseModelOptimizationTest verifies the optimal base DICE model
    %   against the published GAMS benchmark.
    %
    %   Copyright 2024-2026 The MathWorks, Inc.

    methods (TestClassSetup)
        function addSourcePath(testCase)
            projectFolder = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(fullfile(projectFolder, "dice")));
        end
    end

    methods (Test, TestTags="Integration")
        function testMatchesPublishedOptimalGAMSScenario(testCase)
            np = 81;
            params = LoadParams(np);
            benchmark = loadOriginalDiceResults();
            problem = diceFunc(np, params);
            initialPoint.MIU = params.miuup(1:np) - eps;
            initialPoint.S = 0.25*ones(np, 1);
            initialPoint.alpha = [params.a0; 0.4*ones(np-1, 1)];
            options = optimoptions("fmincon", Display="off", ...
                MaxIterations=999000, MaxFunctionEvaluations=999000, ...
                OptimalityTolerance=1e-6, ConstraintTolerance=1e-7, ...
                StepTolerance=1e-8, UseParallel=false);

            solution = solve(problem, initialPoint, Options=options);
            actual = recoverAllVars(solution, params);

            testCase.verifyLessThanOrEqual( ...
                max(abs(actual.("Emissions control rate") - ...
                benchmark.tb{"Emissions control rate", :}')./ ...
                max(1, abs(benchmark.tb{"Emissions control rate", :}'))), 5e-3);
            testCase.verifyLessThanOrEqual( ...
                max(abs(actual.("Savings rate, fraction gross output") - ...
                benchmark.tb{"Savings rate, fraction gross output", :}')./ ...
                max(1, abs(benchmark.tb{"Savings rate, fraction gross output", :}'))), 5e-3);
            testCase.verifyLessThanOrEqual( ...
                max(abs(actual.("Capital stock, 2019$") - ...
                benchmark.tb{"Capital stock, 2019$", :}')./ ...
                max(1, abs(benchmark.tb{"Capital stock, 2019$", :}'))), 5e-3);
            testCase.verifyLessThanOrEqual( ...
                max(abs(actual.("Output, net net trill 2019$") - ...
                benchmark.tb{"Output, net net trill 2019$", :}')./ ...
                max(1, abs(benchmark.tb{"Output, net net trill 2019$", :}'))), 5e-3);
            testCase.verifyLessThanOrEqual( ...
                max(abs(actual.("Atmospheric temperature (deg c above preind)") - ...
                benchmark.tb{"Atmospheric temperature (deg c above preind)", :}')./ ...
                max(1, abs(benchmark.tb{"Atmospheric temperature (deg c above preind)", :}'))), 5e-3);
            testCase.verifyLessThanOrEqual( ...
                max(abs(actual.("Atmospheric concentrations GtC") - ...
                benchmark.tb{"Atmospheric concentrations GtC", :}')./ ...
                max(1, abs(benchmark.tb{"Atmospheric concentrations GtC", :}'))), 5e-3);
        end
    end
end
