name: MATLAB Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: matlab-actions/setup-matlab@v3
        with:
          products: Optimization_Toolbox
      - uses: matlab-actions/run-build@v3
        with:
          tasks: test
